# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'MockedE2EDemo' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['CLANG_WARN_DOCUMENTATION_DEPRECATED_SYNC'] = 'NO'
      end
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
          # Reduce noisy warnings from Pods / RN libraries
          config.build_settings['CLANG_WARN_DOCUMENTATION_DEPRECATED_SYNC'] = 'NO'

          # Suppress common third-party noise
          existing = config.build_settings['OTHER_CFLAGS'] || ['$(inherited)']
          existing = [existing] if existing.is_a?(String)
          config.build_settings['OTHER_CFLAGS'] = existing + [
            '-Wno-nonnull',
            '-Wno-deprecated-declarations'
          ]
        end
    end
  end
end
